
"""Initial clean migration

Revision ID: adec929f1826
Revises: 
Create Date: 2025-10-21
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'adec929f1826'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('subscription_start_date', sa.DateTime(), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.Column('billing_cycle_start', sa.DateTime(), nullable=True),
    sa.Column('billing_cycle_end', sa.DateTime(), nullable=True),
    sa.Column('shobeis_balance', sa.Integer(), server_default='50', nullable=False),
    sa.Column('monthly_balance', sa.Integer(), server_default='50', nullable=False),
    sa.Column('bonus_balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('monthly_refresh_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_refresh_date', sa.DateTime(), nullable=True),
    sa.Column('next_refresh_date', sa.DateTime(), nullable=True),
    sa.Column('total_words_analyzed', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_api_calls', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_exports', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('requests_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shobeis_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_analysis_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_api_usage')
    op.drop_table('user_analytics')
    op.drop_table('user_analysis_stats')
    op.drop_table('shobeis_transactions')
    op.drop_table('blacklisted_tokens')
    op.drop_table('analysis_results')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('action_costs')
    # ### end Alembic commands ###
